# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x05proto\"7\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x11\n\thad_trial\x18\x03 \x01(\x08\"1\n\x11UserCreateRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08username\x18\x02 \x01(\t\"\x14\n\x06UserId\x12\n\n\x02id\x18\x01 \x01(\x03\x32s\n\x0bUserService\x12\x37\n\x0cRegisterUser\x12\x18.proto.UserCreateRequest\x1a\x0b.proto.User\"\x00\x12+\n\x0bGetUserByID\x12\r.proto.UserId\x1a\x0b.proto.User\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=21
  _globals['_USER']._serialized_end=76
  _globals['_USERCREATEREQUEST']._serialized_start=78
  _globals['_USERCREATEREQUEST']._serialized_end=127
  _globals['_USERID']._serialized_start=129
  _globals['_USERID']._serialized_end=149
  _globals['_USERSERVICE']._serialized_start=151
  _globals['_USERSERVICE']._serialized_end=266
# @@protoc_insertion_point(module_scope)
